"""V11 capital allocation review. No purchase. No new experiment."""

V11_ID = "ALPHA_CAPITAL_ALLOCATION_V11"
V11_VERSION = "11.0"
NEW_PURCHASE = False
NEW_DOWNLOAD = False
FINAL_OOS_ACCESS = "DENIED"
DATABENTO_HISTORICAL_SPEND = 31.816129
DATABENTO_REMAINING = 93.0
NEXT_PRIMARY = "CHINA_A_SHARE_RESEARCH_UNIVERSE"
