"""Strategic scores only. Not fake candidate probabilities."""
from __future__ import print_function

from research_engine.v11_alloc import (
    DATABENTO_HISTORICAL_SPEND,
    DATABENTO_REMAINING,
    FINAL_OOS_ACCESS,
    NEW_DOWNLOAD,
    NEW_PURCHASE,
    NEXT_PRIMARY,
    V11_ID,
)


def _route(
    route_id,
    name,
    scores,
    overall,
    candidate_prob,
    candidate_why,
    time_cost,
    cash_usd,
    next_ok,
    why,
):
    return {
        "route_id": route_id,
        "name": name,
        "scores": scores,
        "overall_0_100": overall,
        "candidate_probability": candidate_prob,
        "candidate_probability_basis": candidate_why,
        "research_time": time_cost,
        "cash_usd_this_decision": cash_usd,
        "eligible_as_next": next_ok,
        "why": why,
    }


def build_allocation():
    options = _route(
        "A_MT5_OPTIONS",
        "MT5 + Options surface (LO/OG)",
        {
            "information_novelty": 70,
            "data_availability": 80,
            "cost": 70,
            "expected_research_value": 45,
            "sample_size": 40,
            "mechanism_plausibility": 55,
            "potential_strategy_scale": 25,
            "live_dependency": 20,
        },
        42,
        "LOW",
        "Surface IV/skew/term is untested versus killed GVZ/OVX index. V9/V10 already showed GC/CL structure added 0 Candidates on Ava CFDs. OG option-front never equals futures-front. One-year LO sample. Scale is 1-2 names. EXTERNAL_LIVE_DATA=YES.",
        "small",
        11.99,
        False,
        "Last cheap untested MT5 information class. Not the next dollar: it is still a purchase on an exhausted 4-name CFD book.",
    )
    macro = _route(
        "B_MT5_MACRO_SURPRISE",
        "MT5 + structured macro surprise",
        {
            "information_novelty": 65,
            "data_availability": 20,
            "cost": 25,
            "expected_research_value": 40,
            "sample_size": 50,
            "mechanism_plausibility": 60,
            "potential_strategy_scale": 25,
            "live_dependency": 20,
        },
        35,
        "LOW",
        "actual != surprise. Owned EIA/COT/UST10 were actual-only and already NO_CANDIDATE. Consensus requires a vendor. Same 4-asset universe.",
        "medium",
        None,
        False,
        "Economically real hole. Cannot research now. Do not buy a vendor in this review.",
    )
    events = _route(
        "C_MT5_STRUCTURED_EVENTS",
        "MT5 + structured event data",
        {
            "information_novelty": 60,
            "data_availability": 10,
            "cost": 20,
            "expected_research_value": 30,
            "sample_size": 30,
            "mechanism_plausibility": 50,
            "potential_strategy_scale": 20,
            "live_dependency": 15,
        },
        22,
        "LOW",
        "FOMC/CPI/NFP/OPEC need release timestamp + consensus + surprise. None owned. Event count per year is small. Same 4 CFDs.",
        "large",
        None,
        False,
        "Data requirement only. Not a research start.",
    )
    ashare = _route(
        "D_CHINA_A_SHARE",
        "Freeze MT5 alpha search; open China A-share research universe",
        {
            "information_novelty": 90,
            "data_availability": 75,
            "cost": 90,
            "expected_research_value": 75,
            "sample_size": 85,
            "mechanism_plausibility": 70,
            "potential_strategy_scale": 80,
            "live_dependency": 50,
        },
        72,
        "MEDIUM",
        "Not a claim that A-share has alpha. Basis: MT5 failed because the information set and 4-name universe were exhausted. A-share supplies the missing ingredients (cross-section, industry, statements, announcements) at $0 via BaoStock. Many independent names make the Level 1 >=2-evidence gate feasible. Factor Worker 50-name table is DEMO, not a universe.",
        "large",
        0.0,
        True,
        "Highest information increment per dollar. First work is a free data layer, not a new indicator and not a purchase.",
    )
    other = _route(
        "E_OTHER_MORE_MT5",
        "More MT5 CFD / more Databento / more ML on owned set",
        {
            "information_novelty": 10,
            "data_availability": 90,
            "cost": 40,
            "expected_research_value": 10,
            "sample_size": 60,
            "mechanism_plausibility": 15,
            "potential_strategy_scale": 20,
            "live_dependency": 40,
        },
        15,
        "LOW",
        "V9 unified replay and V10 FDR 0/62 already spent this option. $93 is a reserve, not a budget.",
        "medium",
        0.0,
        False,
        "Forbidden by evidence. Do not spend the Databento remainder on this result.",
    )
    routes = [options, macro, events, ashare, other]
    return {
        "index_id": "V11_CAPITAL_ALLOCATION",
        "discovery_id": V11_ID,
        "NEW_PURCHASE": NEW_PURCHASE,
        "NEW_DOWNLOAD": NEW_DOWNLOAD,
        "FINAL_OOS_ACCESS": FINAL_OOS_ACCESS,
        "spend_this_mission_usd": 0.0,
        "databento_historical_spend_usd": DATABENTO_HISTORICAL_SPEND,
        "databento_remaining_usd": DATABENTO_REMAINING,
        "databento_status": "UNUSED_RESEARCH_RESERVE",
        "options_min_mvd_usd": {"LO_1Y_MVD_A": 11.99, "OG_1Y_MVD_A": 14.99},
        "score_note": "0-100 is strategic ranking only. Not a candidate probability and not a CAGR forecast.",
        "routes": routes,
        "top1": "D_CHINA_A_SHARE",
        "top2": "A_MT5_OPTIONS",
        "top3": "B_MT5_MACRO_SURPRISE",
        "NEXT_PRIMARY_RESEARCH_PATH": NEXT_PRIMARY,
        "next_first_action": "A_SHARE_DATA_LAYER_FREE_BAOSTOCK",
        "next_forbidden": [
            "options purchase",
            "Databento historical purchase",
            "Tushare paid points",
            "ORATS",
            "Wind/Choice/CSMAR subscription",
            "reopen killed MT5 families",
            "new MT5 model on owned set",
        ],
    }
