"""MT5 vs A-share comparison. Inventory only. No download."""
from __future__ import print_function

from research_engine.v11_alloc import NEW_DOWNLOAD, NEW_PURCHASE, V11_ID


ASHARE_SOURCES = [
    {
        "source_id": "BAOSTOCK",
        "cost_class": "FREE",
        "programmatic": True,
        "auth": "login() no registration",
        "history_ohlc": "1990-12-19 to present daily/weekly/monthly",
        "intraday": "5/15/30/60m recent years",
        "fields": [
            "OHLC",
            "preclose",
            "volume",
            "amount",
            "turnover",
            "adjustflag qfq/hfq/none",
            "peTTM pbMRQ psTTM",
            "isST",
            "industry",
            "index constituents",
            "quarterly financials",
            "adjust factor",
        ],
        "frequency": "daily update after 17:30 CST",
        "license": "free personal/research API; not an exchange license",
        "limits": "pandas required; not Xavier 3.6 stdlib; quality must be re-qualified",
        "role": "PRIMARY_CANDIDATE_FOR_FREE_DATA_LAYER",
        "buy": False,
    },
    {
        "source_id": "AKSHARE",
        "cost_class": "FREE_SCRAPE",
        "programmatic": True,
        "auth": "none",
        "history_ohlc": "East Money / Sina / Tencent wrappers",
        "fields": ["OHLC", "spot", "financial abstracts", "notices", "ETF", "index"],
        "frequency": "depends on upstream HTML",
        "license": "academic research disclaimer; upstream ToS",
        "limits": "anti-bot; interface breakage; not a stable immutable source",
        "role": "SECONDARY_CROSS_CHECK_ONLY",
        "buy": False,
    },
    {
        "source_id": "TUSHARE_PRO",
        "cost_class": "FREEMIUM",
        "programmatic": True,
        "auth": "token + points",
        "history_ohlc": "daily from 120 points; adj/financials 2000+; announcements separate paid permission",
        "fields": ["daily", "adj_factor", "income", "balancesheet", "cashflow", "moneyflow"],
        "frequency": "API rate by points",
        "license": "Tushare Pro community; paid tiers exist (200/500/1000 CNY/year documented)",
        "limits": "this review does not buy points",
        "role": "NOT_NOW",
        "buy": False,
    },
    {
        "source_id": "CNINFO_JUCHO",
        "cost_class": "FREE_PUBLIC_FILINGS",
        "programmatic": True,
        "auth": "none for public query pages",
        "history_ohlc": "announcements not bars",
        "fields": ["announcement list", "PDF filings"],
        "frequency": "as filed",
        "license": "CSRC designated disclosure site; bulk redistribution may need SZSI license",
        "limits": "anti-bot; commercial feed is licensed. Research query != licensed tick feed.",
        "role": "ANNOUNCEMENT_LATER",
        "buy": False,
    },
    {
        "source_id": "SSE_SZSE_OFFICIAL",
        "cost_class": "FREE_STATS",
        "programmatic": "partial",
        "auth": "website",
        "fields": ["index", "listed company stats"],
        "limits": "not a full research bar store",
        "role": "REFERENCE",
        "buy": False,
    },
    {
        "source_id": "WIND_CHOICE_CSMAR",
        "cost_class": "PAID",
        "programmatic": True,
        "role": "FORBIDDEN_THIS_REVIEW",
        "buy": False,
    },
]


def build_comparison():
    return {
        "index_id": "V11_MARKET_COMPARISON",
        "discovery_id": V11_ID,
        "NEW_PURCHASE": NEW_PURCHASE,
        "NEW_DOWNLOAD": NEW_DOWNLOAD,
        "mt5": {
            "universe_size": "4 qualified execution names (GOLD EURUSD USDJPY OIL); 841 CFD inventory, all CFD",
            "history": "GOLD/OIL D1 from 2018-12-12 ~7.7y broker-limited; 20260828 frozen",
            "liquidity": "CFD broker book; EXECUTION_APPROXIMATION OHLC+spread",
            "cross_section": "tiny; V5.1 breadth/size on 841 CFDs WEAK_EDGE / NO_CANDIDATE",
            "information_diversity": "price, public actuals, Pack E futures. Options bytes=0. No consensus. No news.",
            "transaction_cost": "V0.6 spread+5bp+10bp; already killed remaining sketches",
            "researchability": "protocol exists; information set exhausted (V9+V10)",
            "expected_alpha_diversity": "LOW remaining",
            "on_disk_research_bars": True,
        },
        "a_share": {
            "universe_size": "5000+ listed names + industries + ETFs + indexes (not yet frozen here)",
            "history": "BaoStock daily from 1990-12-19 claimed; must qualify before use",
            "liquidity": "auction + continuous; T+1; stamp tax on sells",
            "cross_section": "native; this is the missing research dimension",
            "information_diversity": "OHLC, adj, volume, turnover, industry, statements, announcements, ETF structure",
            "transaction_cost": "commission + stamp + impact; higher than FX, but many names",
            "researchability": "no immutable A-share layer yet; Factor Worker 50 names are hardcoded DEMO fundamentals, not bars",
            "expected_alpha_diversity": "HIGH relative to 4 CFDs, UNKNOWN as certified edge",
            "on_disk_research_bars": False,
        },
        "sources": ASHARE_SOURCES,
        "existing_ashare_code": {
            "factor_worker_v1": "50 hardcoded stocks / 15 static factors. Not a data layer. Not a candidate.",
            "immutable_tm_market": "MT5 only. No tm-ashare-* datasets.",
        },
    }
