"""Write-once V15 contract. Frozen before any ranking result."""
from __future__ import print_function

from research_engine.cn_a_share_alpha_v2 import (
    CAGR_TARGET,
    DATASET_HASH,
    DATASET_ID,
    DENIED,
    EXCLUDE_ST,
    FDR_Q,
    FINAL_OOS_ACCESS,
    HOLDS_ALLOWED,
    KEEP_H11_H12,
    LOOKBACKS_ALLOWED,
    MAX_HYPOTHESES,
    MIN_CROSS_SECTION,
    MIN_HISTORY_PAD,
    NEW_H13,
    NEW_PURCHASE,
    PARENT_CONTRACT_HASH,
    QUANTILE,
    REOPEN_H11_H12,
    RESEARCH,
    SAME_CLUSTER_CORR,
    SEED,
    V15_ID,
    VALIDATION,
)
from research_engine.cn_a_share_strategy_v14.cost import COMMISSION, SLIPPAGE, STAMP_NEW, STAMP_OLD, TRANSFER
from research_protocol.hashing import canonical_hash


# Exactly 9. No tenth. No H11/H12 variant. No raw mom/rev/vol/activity.
HYPOTHESES = (
    {
        "id": "H21_RESID_REV_20_H20",
        "family": "CROSS_SECTIONAL_RESIDUAL",
        "mechanism": "Idiosyncratic overreaction after removing the day's EW market. Long lowest residual sum.",
        "lookback": 20,
        "hold_days": 20,
        "state": None,
        "signal": "NEG_RESIDUAL_SUM",
        "not": "RAW_MOMENTUM_OR_RAW_REVERSAL",
    },
    {
        "id": "H22_RESID_REV_60_H20",
        "family": "CROSS_SECTIONAL_RESIDUAL",
        "mechanism": "Same residual reversal, 60-day residual sum.",
        "lookback": 60,
        "hold_days": 20,
        "state": None,
        "signal": "NEG_RESIDUAL_SUM",
        "not": "RAW_MOMENTUM_OR_RAW_REVERSAL",
    },
    {
        "id": "H23_RESID_REV_20_H5",
        "family": "CROSS_SECTIONAL_RESIDUAL",
        "mechanism": "Same residual reversal, 5-day hold. Second registered hold, not a search.",
        "lookback": 20,
        "hold_days": 5,
        "state": None,
        "signal": "NEG_RESIDUAL_SUM",
        "not": "RAW_MOMENTUM_OR_RAW_REVERSAL",
    },
    {
        "id": "H24_DISP_HIGH_RESID_20_H20",
        "family": "MARKET_DISPERSION_STATE",
        "mechanism": "Trade residual-reversal 20 only when CS residual std >= trailing 60d median. Primary state = dispersion level.",
        "lookback": 20,
        "state_lookback": 60,
        "hold_days": 20,
        "state": "DISP_HIGH_MEDIAN_60",
        "signal": "NEG_RESIDUAL_SUM",
        "not": "LOW_VOL_OR_STATE_FACTORY",
    },
    {
        "id": "H25_DISP_UP_RESID_20_H20",
        "family": "MARKET_DISPERSION_STATE",
        "mechanism": "Trade residual-reversal 20 only when residual std is higher than 20 days ago. Dispersion rising.",
        "lookback": 20,
        "state_lookback": 20,
        "hold_days": 20,
        "state": "DISP_RISING_20",
        "signal": "NEG_RESIDUAL_SUM",
        "not": "LOW_VOL_OR_STATE_FACTORY",
    },
    {
        "id": "H26_DISP_HIGH_LOW_BREADTH_20_H20",
        "family": "MARKET_DISPERSION_STATE",
        "mechanism": "Primary HIGH dispersion AND auxiliary LOW breadth (pct-up <= 60d median), then residual-reversal 20.",
        "lookback": 20,
        "state_lookback": 60,
        "hold_days": 20,
        "state": "DISP_HIGH_AND_BREADTH_LOW",
        "signal": "NEG_RESIDUAL_SUM",
        "not": "LOW_VOL_OR_STATE_FACTORY",
    },
    {
        "id": "H27_CAPITULATION_20_H20",
        "family": "PRICE_ACTIVITY_DISAGREEMENT",
        "mechanism": "Price down + activity up. Score = CS rank(-ret_sum_20) + CS rank(amount_sum_20). Long top quintile.",
        "lookback": 20,
        "hold_days": 20,
        "state": None,
        "signal": "RANK_NEG_RET_PLUS_RANK_AMOUNT",
        "not": "SIMPLE_HIGH_OR_LOW_VOLUME",
    },
    {
        "id": "H28_CAPITULATION_60_H20",
        "family": "PRICE_ACTIVITY_DISAGREEMENT",
        "mechanism": "Same capitulation disagreement, 60-day window.",
        "lookback": 60,
        "hold_days": 20,
        "state": None,
        "signal": "RANK_NEG_RET_PLUS_RANK_AMOUNT",
        "not": "SIMPLE_HIGH_OR_LOW_VOLUME",
    },
    {
        "id": "H29_PX_AMT_CORR_20_H20",
        "family": "PRICE_ACTIVITY_DISAGREEMENT",
        "mechanism": "Long names with the most negative 20-day corr(daily ret, dlog amount). Disagreement, not level.",
        "lookback": 20,
        "hold_days": 20,
        "state": None,
        "signal": "NEG_RET_DLOG_AMOUNT_CORR",
        "not": "SIMPLE_HIGH_OR_LOW_VOLUME",
    },
)


def build_contract():
    if len(HYPOTHESES) > MAX_HYPOTHESES:
        raise RuntimeError("TOO_MANY_HYPOTHESES")
    if len(HYPOTHESES) != 9:
        raise RuntimeError("V15_LOCKS_EXACTLY_NINE")
    if any(h["id"].startswith("H11") or h["id"].startswith("H12") or h["id"].startswith("H13") for h in HYPOTHESES):
        raise RuntimeError("H11_H12_H13_FORBIDDEN")
    payload = {
        "id": V15_ID,
        "dataset_id": DATASET_ID,
        "dataset_hash": DATASET_HASH,
        "parent_v13_contract_hash": PARENT_CONTRACT_HASH,
        "live_api": False,
        "new_purchase": NEW_PURCHASE,
        "ml": False,
        "h11_h12": "KEEP_LOW_PRIORITY",
        "reopen_h11_h12": REOPEN_H11_H12,
        "keep_h11_h12": KEEP_H11_H12,
        "new_h13": NEW_H13,
        "excluded": [
            "RAW_MOMENTUM",
            "RAW_REVERSAL",
            "SIMPLE_VOLATILITY",
            "SIMPLE_ACTIVITY",
            "H11_H12_VARIANTS",
            "LOOKBACK_120_180_250",
        ],
        "signal_price": "RAW_CLOSE_T",
        "execution_price": "RAW_OPEN_T1",
        "return_representation": "RAW_CLOSE_TO_CLOSE",
        "representation_risk": "No frozen QFQ. Ranking and PnL use raw prices. DIVIDEND_EXCLUSION.",
        "lookbacks_allowed": list(LOOKBACKS_ALLOWED),
        "holds_allowed": list(HOLDS_ALLOWED),
        "quantile": QUANTILE,
        "portfolio": "QUINTILE_TOP_20",
        "long_only": True,
        "rebalance": "NON_OVERLAPPING_EVERY_HOLD",
        "predictive_formation": "DAILY_OVERLAPPING_H_DAY",
        "predictive_metric_name": "MEAN_FORWARD_RETURN",
        "predictive_is_not_cagr": True,
        "cagr_only_from": "CANONICAL_CAPITAL_ACCOUNT",
        "v14_1_lesson": "Predictive mean != CAGR. Capital account is a separate object.",
        "exclude_st": EXCLUDE_ST,
        "min_history": "lookback + %s" % MIN_HISTORY_PAD,
        "min_cross_section": MIN_CROSS_SECTION,
        "unexecutable": ["LIMIT_LOCK", "SUSPENDED", "DELISTED", "ZERO_VOLUME", "MISSING_OPEN"],
        "unfilled": "WEIGHT_STAYS_CASH_ZERO_PNL_ZERO_FEE",
        "no_forward_fill": True,
        "research": list(RESEARCH),
        "validation": list(VALIDATION),
        "denied_window": list(DENIED),
        "final_oos": FINAL_OOS_ACCESS,
        "split": "70/15/15_TIME",
        "split_note": "Same locked cut as V13/V14: 2010-01-04/2021-08-24 | 2021-08-25/2024-02-29 | 2024-03-01/2026-08-28.",
        "fdr_q": FDR_Q,
        "seed": SEED,
        "bootstrap": {"iid": 1000, "block": 1000, "block_len": 20, "seed": SEED},
        "permutation": {"n": 100, "seed": SEED},
        "cost_model": {
            "id": "A_SHARE_STRATEGY_COST_MODEL_V1",
            "parent": "A_SHARE_TRANSACTION_COST_MODEL_V1",
            "commission": COMMISSION,
            "transfer": TRANSFER,
            "slippage": SLIPPAGE,
            "stamp_before_20230828": STAMP_OLD,
            "stamp_from_20230828": STAMP_NEW,
            "stamp_side": "SELL_ONLY",
            "not": "MT5_5BP_10BP",
            "optimize": False,
        },
        "benchmarks": ["B0_EW_ELIGIBLE", "B1_RANDOM_QUINTILE"],
        "same_cluster_corr": SAME_CLUSTER_CORR,
        "cagr_target_not_a_gate": CAGR_TARGET,
        "level1": [
            "pre_registered",
            "research_MEAN_FORWARD_RETURN_net > 0",
            "validation_MEAN_FORWARD_RETURN_net > 0",
            "BH_FDR_q_0.05",
            ">=2 evidence (excess_vs_B0 and rank_ic) on research AND validation",
            "PIT_clean",
            "research_capital_total > 0",
            "validation_capital_total > 0",
        ],
        "do_not_flip_sign": True,
        "no_tenth_hypothesis": True,
        "preregistered_run_all_nine": True,
        "preregistered_run_note": (
            "All 9 are the experiment. Completing the registered set is not a new search. "
            "No H10. A hit does not authorize extra hypotheses."
        ),
        "hypotheses": [dict(h) for h in HYPOTHESES],
    }
    payload["contract_hash"] = canonical_hash(payload)
    return payload
