"""Historical mechanism registry. Replay only. No new hypotheses."""
from __future__ import print_function

# replay_kind:
#   STRATEGY_REPLAY   - locked entry/exit book
#   PREDICTIVE_ONLY   - not a trading strategy; no CAGR
#   FACTOR_ONLY       - factor performance only
#   ALPHA_TEST        - costed diagnostic / residual; book if entry/exit exists

MECHANISMS = [
    {
        "family": "HYP-0001",
        "class": "Directional",
        "replay_kind": "PREDICTIVE_ONLY",
        "information_set": "IS-A",
        "module": None,
        "space_file": None,
        "live_external": "NO",
        "note": "Frozen 14:11 predictive contract. Not a book. Do not invent CAGR.",
    },
    {
        "family": "FACTOR_DISCOVERY_V0.1",
        "class": "Momentum",
        "replay_kind": "FACTOR_ONLY",
        "information_set": "IS-A",
        "module": "discovery",
        "space_file": "factor_discovery/FACTOR_SEARCH_SPACE_V0.1.json",
        "live_external": "NO",
        "note": "Factor zoo. Not a strategy.",
    },
    {
        "family": "STRATEGY_DISCOVERY_V0.5",
        "class": "Directional",
        "replay_kind": "PREDICTIVE_ONLY",
        "information_set": "IS-A",
        "module": "strategy",
        "space_file": "strategy_discovery/STRATEGY_SEARCH_SPACE_V0.5.json",
        "live_external": "NO",
        "note": "NEXT_CLOSED_BAR close-to-close screen. Not a trade book.",
    },
    {
        "family": "PROFIT_DISCOVERY_V0.6",
        "class": "Momentum",
        "replay_kind": "STRATEGY_REPLAY",
        "information_set": "IS-A",
        "module": "profit",
        "space_file": "profit_discovery/PROFIT_SEARCH_SPACE_V0.6.json",
        "live_external": "NO",
        "note": "Canonical NEXT_BAR_OPEN path book.",
    },
    {
        "family": "CROSS_ASSET_V0.8",
        "class": "Cross Asset",
        "replay_kind": "STRATEGY_REPLAY",
        "information_set": "IS-A",
        "module": "cross_asset",
        "space_file": "cross_asset/CROSS_ASSET_SEARCH_SPACE_V0.8.json",
        "live_external": "NO",
        "special": "cross_asset",
    },
    {
        "family": "REGIME_TRANSITION_V0.9",
        "class": "Regime Transition",
        "replay_kind": "STRATEGY_REPLAY",
        "information_set": "IS-A",
        "module": "regime_transition",
        "space_file": "regime_transition/REGIME_TRANSITION_SEARCH_SPACE_V0.9.json",
        "live_external": "NO",
    },
    {
        "family": "CROSS_RESIDUAL_V0.91",
        "class": "Mean Reversion",
        "replay_kind": "STRATEGY_REPLAY",
        "information_set": "IS-A",
        "module": "cross_residual",
        "space_file": "cross_residual/CROSS_RESIDUAL_SEARCH_SPACE_V0.91.json",
        "live_external": "NO",
        "special": "residual",
    },
    {
        "family": "INSTITUTIONAL_TIME_V1.0",
        "class": "Calendar",
        "replay_kind": "STRATEGY_REPLAY",
        "information_set": "IS-A",
        "module": "institutional_time",
        "space_file": "institutional_time/IT_SEARCH_SPACE_V1.0.json",
        "live_external": "NO",
    },
    {
        "family": "TIME_STRUCTURE_V1",
        "class": "Calendar",
        "replay_kind": "STRATEGY_REPLAY",
        "information_set": "IS-A",
        "module": "time_structure",
        "space_file": "time_structure/TS_SEARCH_SPACE_V1.json",
        "live_external": "NO",
    },
    {
        "family": "MICROSTRUCTURE_SURPRISE_V1",
        "class": "Breakout",
        "replay_kind": "STRATEGY_REPLAY",
        "information_set": "IS-A",
        "module": "microstructure_surprise",
        "space_file": "microstructure_surprise/MS_SEARCH_SPACE_V1.json",
        "live_external": "NO",
    },
    {
        "family": "REGIME_INTERACTION_V1",
        "class": "Regime",
        "replay_kind": "STRATEGY_REPLAY",
        "information_set": "IS-A",
        "module": "regime_interaction",
        "space_file": "regime_interaction/RI_SEARCH_SPACE_V1.json",
        "live_external": "NO",
    },
    {
        "family": "ALT_MARKET_STRUCTURE_V1",
        "class": "Calendar",
        "replay_kind": "STRATEGY_REPLAY",
        "information_set": "IS-A",
        "module": "alt_market_structure",
        "space_file": "alt_market_structure/AMS_SEARCH_SPACE_V1.json",
        "live_external": "NO",
    },
    {
        "family": "IMPLIED_VOL_V1",
        "class": "Regime",
        "replay_kind": "STRATEGY_REPLAY",
        "information_set": "IS-B",
        "module": "implied_vol",
        "space_file": "implied_vol/IV_SEARCH_SPACE_V1.json",
        "live_external": "YES",
        "public_source": "CBOE_GVZ_OVX",
    },
    {
        "family": "POSITIONING_V1",
        "class": "COT",
        "replay_kind": "STRATEGY_REPLAY",
        "information_set": "IS-B",
        "module": "positioning",
        "space_file": "positioning/POS_SEARCH_SPACE_V1.json",
        "live_external": "YES",
        "public_source": "CFTC_COT",
    },
    {
        "family": "INVENTORY_V1",
        "class": "EIA",
        "replay_kind": "STRATEGY_REPLAY",
        "information_set": "IS-B",
        "module": "inventory",
        "space_file": "inventory/INV_SEARCH_SPACE_V1.json",
        "live_external": "YES",
        "public_source": "EIA_STOCKS",
    },
    {
        "family": "RATES_V1",
        "class": "Rates",
        "replay_kind": "STRATEGY_REPLAY",
        "information_set": "IS-B",
        "module": "rates",
        "space_file": "rates/RATES_SEARCH_SPACE_V1.json",
        "live_external": "YES",
        "public_source": "UST10",
    },
    {
        "family": "CARRY_V1A",
        "class": "Rates",
        "replay_kind": "STRATEGY_REPLAY",
        "information_set": "IS-B",
        "module": "carry",
        "space_file": "carry_v1a/CARRY_SEARCH_SPACE_V1A.json",
        "live_external": "YES",
        "public_source": "EFFR_ESTR_BOJ",
    },
    {
        "family": "SUPPLY_V1",
        "class": "EIA",
        "replay_kind": "STRATEGY_REPLAY",
        "information_set": "IS-B",
        "module": "supply",
        "space_file": "supply/SUP_SEARCH_SPACE_V1.json",
        "live_external": "YES",
        "public_source": "EIA_SUPPLY",
    },
    {
        "family": "CROSS_METAL_V1",
        "class": "Cross Asset",
        "replay_kind": "STRATEGY_REPLAY",
        "information_set": "IS-B",
        "module": "cross_metal",
        "space_file": "cross_metal/CM_SEARCH_SPACE_V1.json",
        "live_external": "NO",
        "note": "Extra owned MT5 SILVER CFD used as information. Not Databento.",
    },
    {
        "family": "USD_METAL_V1",
        "class": "Cross Asset",
        "replay_kind": "STRATEGY_REPLAY",
        "information_set": "IS-B",
        "module": "usd_metal",
        "space_file": "usd_metal/UM_SEARCH_SPACE_V1.json",
        "live_external": "NO",
        "note": "Owned MT5 DXY CFD. Not Databento.",
    },
    {
        "family": "XS_REV_V1",
        "class": "Cross Section",
        "replay_kind": "STRATEGY_REPLAY",
        "information_set": "IS-B",
        "module": "xs_rev",
        "space_file": "xs_rev/XS_SEARCH_SPACE_V1.json",
        "live_external": "NO",
    },
    {
        "family": "CORR_SHOCK_V1",
        "class": "Cross Asset",
        "replay_kind": "STRATEGY_REPLAY",
        "information_set": "IS-B",
        "module": "corr_shock",
        "space_file": "corr_shock/CS_SEARCH_SPACE_V1.json",
        "live_external": "NO",
    },
    {
        "family": "ENERGY_RV_V1",
        "class": "Cross Asset",
        "replay_kind": "STRATEGY_REPLAY",
        "information_set": "IS-B",
        "module": "energy_rv",
        "space_file": "energy_rv/ER_SEARCH_SPACE_V1.json",
        "live_external": "NO",
    },
    {
        "family": "VOL_TERM_V1",
        "class": "Regime",
        "replay_kind": "STRATEGY_REPLAY",
        "information_set": "IS-B",
        "module": "vol_term",
        "space_file": "vol_term/VT_SEARCH_SPACE_V1.json",
        "live_external": "NO",
    },
    {
        "family": "IDX_ASYNC_V1",
        "class": "Cross Asset",
        "replay_kind": "STRATEGY_REPLAY",
        "information_set": "IS-B",
        "module": "idx_async",
        "space_file": "idx_async/IA_SEARCH_SPACE_V1.json",
        "live_external": "NO",
    },
    {
        "family": "BREADTH_V1",
        "class": "Breadth",
        "replay_kind": "STRATEGY_REPLAY",
        "information_set": "IS-B",
        "module": "breadth",
        "space_file": "breadth/BR_SEARCH_SPACE_V1.json",
        "live_external": "NO",
    },
    {
        "family": "SIZE_SPREAD_V1",
        "class": "Cross Section",
        "replay_kind": "STRATEGY_REPLAY",
        "information_set": "IS-B",
        "module": "size_spread",
        "space_file": "size_spread/SZ_SEARCH_SPACE_V1.json",
        "live_external": "NO",
    },
    {
        "family": "TERM_STRUCTURE_V1",
        "class": "Futures",
        "replay_kind": "STRATEGY_REPLAY",
        "information_set": "IS-C",
        "module": "term_structure",
        "space_file": "term_structure/TS_SEARCH_SPACE_V1.json",
        "live_external": "YES",
        "futures_source": "PACK_E_CURVE",
    },
    {
        "family": "FUTURES_OI_FLOW_V1",
        "class": "OI",
        "replay_kind": "STRATEGY_REPLAY",
        "information_set": "IS-C",
        "module": "futures_oi",
        "space_file": "futures_oi/OI_SEARCH_SPACE_V1.json",
        "live_external": "YES",
        "futures_source": "PACK_E_OI",
    },
    {
        "family": "VOLUME_PRICE_FLOW_V1",
        "class": "Futures",
        "replay_kind": "STRATEGY_REPLAY",
        "information_set": "IS-C",
        "module": "futures_vol",
        "space_file": "futures_vol/VOL_SEARCH_SPACE_V1.json",
        "live_external": "YES",
        "futures_source": "PACK_E_VOLUME",
    },
    {
        "family": "DTE_ROLL_WINDOW_V1",
        "class": "DTE",
        "replay_kind": "STRATEGY_REPLAY",
        "information_set": "IS-C",
        "module": "futures_dte",
        "space_file": "futures_dte/DTE_SEARCH_SPACE_V1.json",
        "live_external": "YES",
        "futures_source": "PACK_E_DTE",
    },
    {
        "family": "FUT_CFD_LEAD_V1",
        "class": "Futures",
        "replay_kind": "STRATEGY_REPLAY",
        "information_set": "IS-D",
        "module": "fut_cfd",
        "space_file": "fut_cfd/FUTCFD_SEARCH_SPACE_V1.json",
        "live_external": "YES",
        "futures_source": "PACK_E_SETTLEMENT",
    },
    {
        "family": "CURVE_OI_JOINT_V1",
        "class": "Futures",
        "replay_kind": "STRATEGY_REPLAY",
        "information_set": "IS-D",
        "module": "curve_oi",
        "space_file": "curve_oi/CUROI_SEARCH_SPACE_V1.json",
        "live_external": "YES",
    },
    {
        "family": "OI_COT_BUILD_V1",
        "class": "COT",
        "replay_kind": "STRATEGY_REPLAY",
        "information_set": "IS-D",
        "module": "oi_cot",
        "space_file": "oi_cot/OICOT_SEARCH_SPACE_V1.json",
        "live_external": "YES",
    },
    {
        "family": "CURVE_EIA_REPRICE_V1",
        "class": "EIA",
        "replay_kind": "STRATEGY_REPLAY",
        "information_set": "IS-D",
        "module": "curve_eia",
        "space_file": "curve_eia/CUEIA_SEARCH_SPACE_V1.json",
        "live_external": "YES",
    },
    {
        "family": "CURVE_REALYIELD_V1",
        "class": "Rates",
        "replay_kind": "STRATEGY_REPLAY",
        "information_set": "IS-D",
        "module": "curve_rate",
        "space_file": "curve_rate/CURATE_SEARCH_SPACE_V1.json",
        "live_external": "YES",
    },
]


def strategy_families():
    return [m for m in MECHANISMS if m["replay_kind"] == "STRATEGY_REPLAY"]


def by_information_set(code):
    return [m for m in MECHANISMS if m["information_set"] == code]
