"""Auto-generate REPORT.md (11 sections) ending in WHY_RESULT_HAPPENED. Explains, never claims alpha."""
from __future__ import print_function


def _g(d, k, default="UNKNOWN"):
    v = (d or {}).get(k)
    return default if v is None else v


def _keys(d):
    return sorted((d or {}).keys(), key=lambda x: str(x))


def _fmt(v):
    if isinstance(v, float):
        return "%.4f" % v
    return str(v)


def build_report(manifest, config, data_lineage, data_snapshot, signals_summary,
                 metrics, attribution_map, error_result):
    m = manifest or {}
    lines = []
    A = lines.append
    A("# A-Short Experiment REPORT")
    A("")
    A("> Auto-generated by `cn_a_short/forensic`. Observability only — does not change results, "
      "does not claim alpha or trading readiness.")
    A("")

    # 1
    A("## 1. Run Summary")
    A("- run_id: `%s`" % _g(m, "run_id"))
    A("- status: `%s`" % _g(m, "status"))
    A("- git_commit: `%s`  branch: `%s`  dirty: `%s`" % (_g(m, "git_commit"), _g(m, "branch"), _g(m, "dirty")))
    A("- python: `%s`  os: `%s`  deps: `%s`" % (_g(m, "python_version"), _g(m, "os"), _g(m, "dependencies")))
    A("- manifest_hash (semantic): `%s`" % _g(m, "manifest_hash"))
    A("")

    # 2
    A("## 2. Data")
    A("- upstream: `%s` / `%s`" % (_g(m, "upstream_dataset_id"), _g(m, "upstream_hash")))
    A("- derived: `%s` / `%s`" % (_g(m, "derived_dataset_id"), _g(m, "derived_dataset_hash")))
    A("- data_status: `%s`" % _g(data_lineage, "data_status"))
    cov = (data_lineage or {}).get("coverage") or {}
    if cov:
        A("- coverage: finite_close_when_listed=`%s` degenerate=`%s`" %
          (_fmt(_g(cov, "finite_close_rate_when_listed")), _g(cov, "degenerate")))
    A("")

    # 3
    A("## 3. Universe")
    ds = data_snapshot or {}
    if ds.get("available"):
        A("- asof: `%s`  total_listed: `%s`  eligible: `%s`" %
          (_g(ds, "asof"), _g(ds, "total_listed_symbols"), _g(ds, "eligible_symbols")))
        A("- boards: `%s`  ST: `%s`  suspended: `%s`  limit_hits: `%s`" %
          (_g(ds, "board_composition"), _g(ds, "st_count"), _g(ds, "suspended_count"), _g(ds, "limit_hit_count")))
        A("- price_distribution: `%s`" % _g(ds, "price_distribution"))
        A("- amount_distribution: `%s`" % _g(ds, "amount_distribution"))
        A("- market_cap: `%s` (UNKNOWN — no shares-outstanding data)" % _g(ds, "market_cap"))
        A("> Junk-stock check: inspect board mix + price/amount percentiles before crediting returns to selection.")
    else:
        A("- DATA_SNAPSHOT unavailable (`%s`); universe composition UNKNOWN." % _g(ds, "reason"))
    A("")

    # 4
    A("## 4. Model")
    A("- model: `%s` / `%s` (baseline only; NOT final strategy)" % (_g(m, "model_id"), _g(m, "model_version")))
    A("- execution_version: `%s`  cost_version: `%s`" % (_g(m, "execution_version"), _g(m, "cost_version")))
    A("- universe_definition: `%s`" % _g(m, "universe_definition"))
    A("")

    # 5
    A("## 5. Execution")
    er = error_result or {}
    lc = (metrics or {}).get("lifecycle") or {}
    if lc:
        A("- lifecycle terminal_counts: `%s`  all_complete=`%s`" %
          (_g(lc, "terminal_counts"), _g(lc, "all_complete")))
    else:
        A("- lifecycle: UNKNOWN (no filled periods)")
    A("")

    # 6
    A("## 6. Cost")
    A("- cost model = canonical (commission min ¥5 / transfer / stamp / slippage assumption). "
      "See COST_FEASIBILITY_V2.")
    A("")

    # 7
    A("## 7. Performance")
    mk = (metrics or {}).get("by_k") or {}
    if mk:
        A("| Bucket | gross_topk | gross_ew | excess_vs_ew | t_excess | strategy_net |")
        A("|---|---|---|---|---|---|")
        for k in _keys(mk):
            r = mk[k]
            A("| %s | %s | %s | %s | %s | %s |" % (
                k, _fmt(_g(r, "mean_gross_topk")), _fmt(_g(r, "mean_gross_ew")),
                _fmt(_g(r, "mean_excess_vs_ew")), _fmt(_g(r, "t_excess")), _fmt(_g(r, "strategy_total_net"))))
    else:
        A("- performance: UNKNOWN (no empirical result / DATA_BLOCKED)")
    A("")

    # 8
    A("## 8. Attribution (APPROX)")
    if attribution_map:
        for k in _keys(attribution_map):
            a = attribution_map[k]
            A("- %s: market_beta=`%s` size=`%s` momentum=`%s` selection=`%s`" % (
                k, _fmt(_g(a, "market_beta")), _g(a, "size_effect"),
                _fmt((a.get("momentum_effect") or {}).get("value")), _g(a, "selection_effect")))
        A("> size/selection = UNKNOWN (no market-cap/factor model). If excess≈0 → return is beta, not alpha.")
    else:
        A("- attribution: UNKNOWN (no empirical result)")
    A("")

    # 9
    A("## 9. Failure Diagnosis")
    A("- primary_conclusion: **%s**" % _g(er, "primary_conclusion"))
    for e in (er.get("errors") or []):
        A("- [%s/%s/%s] %s | evidence=`%s`" % (
            e.get("class"), e.get("error_code"), e.get("severity"), e.get("message"), e.get("evidence")))
    if not (er.get("errors")):
        A("- no classified errors")
    A("")

    # 10
    A("## 10. Reproducibility")
    A("- reproduction: `python -m research_engine.cn_a_short.run_baseline` (same seed=%s, windows fixed)" %
      _g(m, "seed"))
    A("- semantic manifest_hash: `%s` (excludes time/commit/env)" % _g(m, "manifest_hash"))
    A("")

    # 11
    A("## 11. Decision")
    A("- Alpha: NOT PROVEN. Trading: NOT AUTHORIZED. This is baseline + observability only.")
    A("")

    # WHY
    A("## WHY_RESULT_HAPPENED")
    A(_why(er, metrics))
    A("")
    return "\n".join(lines)


def _why(error_result, metrics):
    er = error_result or {}
    primary = er.get("primary_conclusion")
    mapping = {
        "DATA_BLOCKED": "数据问题：冻结 D1 面板未物化，无 empirical 结果（不是策略结论）。",
        "DEGENERATE_PANEL": "数据问题：面板全 NaN（退化），无有效价格。",
        "STYLE_EXPOSURE_ONLY": "alpha 失败/风格暴露：毛收益为正但超额 vs EW 不显著 → 收益主要是小盘/市场 β，不是 selection alpha。",
        "TRUE_NO_EDGE": "无边：毛/超额/净收益均不显著，执行与成本正常 → 该信号无短线 edge。",
        "COST_ERROR": "成本问题：毛正但净负 → 换手×成本吞噬收益。",
        "SIGNIFICANT_EXCESS_PENDING_AUDIT": "出现显著超额，但需进一步审计（泄漏/幸存者/执行/重复检验）后才可下结论，禁止直接当 alpha。",
        "INCONCLUSIVE": "证据不足以定性；需更多数据/期数。",
    }
    base = mapping.get(primary, "结论：%s" % primary)
    cats = sorted(set(e.get("class") for e in (er.get("errors") or [])))
    if cats:
        base += " 归类：" + " / ".join(cats) + "。"
    base += " （亏损/异常必须归入：alpha失败 / 数据问题 / 执行问题 / 成本问题 / 环境问题 之一——见上。）"
    return base


__all__ = ["build_report"]
