"""Pre-scored research questions. Mechanisms, not indicators. Scores frozen before any new PnL."""
from __future__ import print_function


def _q(rid, mechanism, why, data, fail, e, d, crowd, c, t, cluster, flags=None):
    flags = flags or {}
    return {
        "id": rid,
        "mechanism": mechanism,
        "why_exists": why,
        "required_data": data,
        "expected_failure_mode": fail,
        "economic_plausibility": e,
        "data_availability": d,
        "crowding": crowd,
        "cost_survivability": c,
        "testability": t,
        "cluster": cluster,
        "killed_isomorph": bool(flags.get("killed")),
        "data_blocked": bool(flags.get("blocked")),
        "v09_member": bool(flags.get("v09")),
        "contract_eligible": not bool(flags.get("meta")),
    }


def all_questions():
    D1 = "GOLD/OIL/FX D1 OHLCV+spread, UTC"
    ALN = "four D1 inner join 1993 days + parent hashes"
    BLK = "not on disk"
    return [
        _q("RB-0001",
           "Risk books cut energy risk after a realized vol jump; liquidation continues for several days.",
           "VaR/vol targets are discrete. They reset on a shock, not smoothly every bar.",
           D1 + "; V0.5 VOL percentiles",
           "Only 2020 oil extremes; or same as always-short OIL.",
           4, 5, 2, 4, 4, "REGIME_TRANSITION", {"v09": True}),
        _q("RB-0002",
           "Trend-following capital enters after strength ignites, not on every in-trend bar.",
           "CTA/risk-on flows are delayed by committees and signals that need confirmation.",
           D1 + "; SMA20/50 + ADX14",
           "Occupancy looks like state-level TREND_STRONG (V0.6 already killed).",
           4, 5, 2, 4, 4, "REGIME_TRANSITION", {"v09": True}),
        _q("RB-0003",
           "When trend strength dies, levered longs de-risk; the exit is clustered.",
           "Stops and risk reductions fire at the change, not at every WEAK bar.",
           D1 + "; ADX14",
           "Just unconditional gold short in a bear tape.",
           4, 5, 2, 4, 4, "REGIME_TRANSITION", {"v09": True}),
        _q("RB-0004",
           "Gold is bought as a haven on the same vol shock that dumps oil.",
           "Flight-to-safety is a different book from energy de-risking.",
           D1,
           "Conflicts with RB-0001 in one FDR family; gold bull path looks like alpha.",
           3, 5, 3, 4, 3, "REGIME_TRANSITION"),
        _q("RB-0005",
           "Weekend information is priced on Sunday/Monday D1, not evenly across weekdays.",
           "Human and official calendars are weekly. Positions are squared before the weekend.",
           "D1 timestamps; Sunday bars exist on this broker",
           "Few events; holiday confounding; gold path.",
           3, 5, 3, 4, 3, "CALENDAR"),
        _q("RB-0006",
           "Friday flattening creates a weekend risk-off premium that reverses after the gap.",
           "Dealers do not want weekend inventory.",
           D1 + " weekday labels",
           "Same as RB-0005 with a different weekday dummy — multiple-testing twin.",
           3, 5, 4, 4, 3, "CALENDAR"),
        _q("RB-0007",
           "Month-end rebalancing moves gold and FX as funds match benchmarks.",
           "Index and CTA rebalance dates are public constraints.",
           D1 + " calendar",
           "6.4y ≈ 77 month-ends; weak power; easy to overfit day windows.",
           3, 5, 4, 4, 2, "CALENDAR"),
        _q("RB-0008",
           "Quarter-end window dressing moves the same books harder than month-end.",
           "Reporting dates are harder constraints than month-end.",
           D1 + " calendar",
           "Only ~25 quarters; INSUFFICIENT_OCCUPANCY likely.",
           3, 5, 4, 4, 2, "CALENDAR"),
        _q("RB-0009",
           "Gold and oil share a slow risk/inflation link; the log-ratio residual mean-reverts after extremes.",
           "Two real assets, one macro factor. Inventory and positioning pull the spread back.",
           ALN,
           "Just a 2020-2022 inflation tape; or V0.8 dollar proxy in disguise.",
           4, 4, 2, 3, 3, "RESIDUAL"),
        _q("RB-0010",
           "Gold versus a frozen FX basket residual (not next-day Q3) mean-reverts over several days.",
           "Gold is priced in dollars; the slow gap is not the one-day V0.8 claim.",
           ALN,
           "Decision 043 temptation: same family with a longer lag.",
           3, 4, 2, 3, 3, "RESIDUAL"),
        _q("RB-0011",
           "After a correlation spike, the leftover residual is more tradable than outright legs.",
           "In stress, betas go to one; the orthogonal leftover is what desks still warehouse.",
           ALN,
           "Contemporaneous corr used as a trade (V0.8 diagnostic trap).",
           3, 4, 3, 3, 3, "CORR_SHIFT"),
        _q("RB-0012",
           "Holiday-missing Fridays create an information gap that the next aligned row over-prices.",
           "This broker skips some holiday Fridays. The next print is a catch-up auction.",
           "D1 holiday-skip list from XA audit",
           "Too few dates; OIL 2020 dominates.",
           3, 4, 2, 4, 2, "CALENDAR"),
        _q("RB-0013",
           "Wide spread is a rationing state: new risk is not taken, existing risk is dumped slowly.",
           "Dealers widen to refuse inventory, not to print a directional signal.",
           "spread series already on every bar",
           "FD already killed spread-as-direction. Overlay-as-profit killed in V0.6 DEF.",
           2, 5, 2, 3, 4, "LIQUIDITY", {"killed": True}),
        _q("RB-0014",
           "Tick-activity drought means the next move is a gap, not a walk.",
           "Thin books jump when the next informed order arrives.",
           "tick_volume only",
           "FD tick-z failed; real_volume is zero.",
           2, 3, 3, 2, 3, "LIQUIDITY", {"killed": True}),
        _q("RB-0015",
           "Carry: rate differential is paid to whoever holds the high-yield currency.",
           "Central banks set a transfer. Price can drift to pay it.",
           BLK + " (rates/swap)",
           "Price momentum dressed as carry.",
           4, 1, 3, 5, 4, "CARRY", {"blocked": True}),
        _q("RB-0016",
           "Implied vol is rich versus later realized vol; selling that gap is a premium.",
           "Option demand for insurance is structural.",
           BLK + " (IV)",
           "ATR used as fake IV.",
           4, 1, 3, 4, 3, "VRP", {"blocked": True}),
        _q("RB-0017",
           "Scheduled CPI/NFP prints a risk premium in the hours around the event.",
           "Uncertainty is resolved on a clock. Someone is paid to hold it.",
           BLK + " (calendar file)",
           "Post-hoc labels on big down days.",
           3, 1, 3, 3, 3, "EVENT", {"blocked": True}),
        _q("RB-0018",
           "EIA inventory prints reprice oil after a delay as physical desks update.",
           "Physical quantity is news; paper price is a noisy map.",
           BLK + " (EIA table)",
           "Same as guessing oil direction from oil.",
           3, 1, 3, 3, 3, "EVENT", {"blocked": True}),
        _q("RB-0019",
           "Session open of London/NY concentrates inventory transfer; the first hour is not a random walk.",
           "Human trading hours still dominate FX/gold.",
           "long M15/H1 (not 2000-bar month)",
           "One-month M15 will print a fake seasonality.",
           3, 1, 4, 2, 2, "SEASONALITY", {"blocked": True}),
        _q("RB-0020",
           "True order-flow imbalance predicts the next trade, not the next daily bar.",
           "Someone must take the other side of a large order.",
           BLK + " (DOM / real_volume)",
           "tick_volume replay of FD.",
           4, 1, 3, 2, 2, "ORDER_FLOW", {"blocked": True}),
        _q("RB-0021",
           "After both gold and oil gap down together, the slower residual still mean-reverts.",
           "Common factor shock plus an idiosyncratic leftover.",
           ALN,
           "Two-leg costs eat the leftover.",
           3, 4, 2, 2, 3, "RESIDUAL"),
        _q("RB-0022",
           "USDJPY and EURUSD disagreement (one says dollar up, one does not) is a noisy-dollar day; gold should not be traded on it.",
           "Avoiding bad dollar days is a filter, not a signal farm.",
           ALN,
           "Becomes XA-0004.",
           2, 4, 2, 3, 3, "MULTI_ASSET", {"killed": True}),
        _q("RB-0023",
           "A second asset confirming a breakout reduces fake-outs from one book’s stop run.",
           "Stops cluster on one chart; they do not cluster on two independent books.",
           ALN,
           "Donchian with extra steps (V0.6 isomorph).",
           2, 4, 4, 2, 3, "PRICE_FORMATION", {"killed": True}),
        _q("RB-0024",
           "Short-horizon same-sign streaks are a tiny continuation premium.",
           "Under-reaction for a few bars.",
           "any OHLCV",
           "HYP-0001 already measured this. Not a book.",
           2, 5, 5, 1, 5, "PRICE_FORMATION", {"killed": True}),
        _q("RB-0025",
           "Price far from a short moving center snaps back because market-makers lean against inventory.",
           "Dealers fade extremes they created.",
           "OHLCV",
           "V0.6 MR-Z20 / FD reversal.",
           2, 5, 5, 1, 4, "PRICE_FORMATION", {"killed": True}),
        _q("RB-0026",
           "A new high after a quiet range is a stop cascade that continues one more bar.",
           "Stops sit above the range.",
           "OHLCV",
           "V0.6 TF-BRK20.",
           2, 5, 5, 1, 4, "PRICE_FORMATION", {"killed": True}),
        _q("RB-0027",
           "Being in TREND_STRONG is a filter that makes breakouts cleaner.",
           "State as permission, not as a change.",
           "V0.5 state",
           "V0.5/V0.6 level filter. Occupancy too high.",
           2, 5, 4, 2, 4, "REGIME_LEVEL", {"killed": True}),
        _q("RB-0028",
           "Skipping HIGH_VOL days is itself a return source.",
           "Insurance by not playing.",
           "ATR/VOL",
           "V0.6 DEF: 0 trades, 0 return. Not profit.",
           1, 5, 3, 5, 5, "RISK_OVERLAY", {"killed": True}),
        _q("RB-0029",
           "Equal-weight three weak same-symbol sleeves diversifies noise.",
           "If errors are independent, variance falls.",
           "V0.6 three curves",
           "Errors were the same cost and the same bars. Book went more negative.",
           1, 5, 3, 2, 4, "PORTFOLIO", {"killed": True}),
        _q("RB-0030",
           "Scale a surviving sleeve to target realized vol so the edge is not eaten in wild months.",
           "Risk units, not shares, are what PMs allocate.",
           "ATR + a Level 1 sleeve",
           "No sleeve yet. Standalone it is DEF again.",
           3, 2, 2, 4, 4, "RISK_4A"),
        _q("RB-0031",
           "Buy-and-hold gold harvests a scarcity/risk premium over years.",
           "Positive supply shock is rare; real rates and geopolitics pay a holder.",
           "GOLD D1",
           "2020-2026 path is not a conditional edge. PATH_BENCHMARK only.",
           2, 5, 5, 5, 5, "PATH_BENCHMARK", {"meta": True}),
        _q("RB-0032",
           "Buy-and-hold oil harvests a scarcity premium.",
           "Energy is consumed; disruptions are fat-tailed.",
           "OIL D1",
           "2020 crash dominates any premium story.",
           2, 5, 5, 5, 5, "PATH_BENCHMARK", {"meta": True}),
        _q("RB-0033",
           "After vol leaves HIGH, risk appetite returns and oil mean-reverts up.",
           "The inverse of the shock cut: budgets reopen.",
           D1,
           "Sparser than RB-0001; do not add as 4th V0.9 id.",
           3, 5, 2, 4, 3, "REGIME_TRANSITION"),
        _q("RB-0034",
           "Down-trend ignition (WEAK→STRONG and TREND=DOWN) continues gold lower.",
           "Symmetric to RB-0002.",
           D1,
           "Pair-scan with 0002. Keep off m=3.",
           3, 5, 2, 4, 3, "REGIME_TRANSITION"),
        _q("RB-0035",
           "FX trend ignition continues EURUSD for several days.",
           "Same delayed-CTA story on G10.",
           "EURUSD D1",
           "Expands V0.9 universe; contract locked GOLD/OIL only.",
           3, 5, 3, 4, 3, "REGIME_TRANSITION"),
        _q("RB-0036",
           "A nonlinear combination of a few causal states beats linear Δstate.",
           "Interactions can be real. Infinite features are not.",
           D1 + " local LLM optional",
           "Unregistered feature farm. FDR explodes.",
           3, 3, 2, 2, 2, "ML"),
        _q("RB-0037",
           "LLM reads a dated macro text and shifts gold’s next-week expectation.",
           "Language can carry constraints the price series already used.",
           BLK + " timestamped text",
           "Leakage via undated news. Not this quarter.",
           3, 1, 2, 3, 1, "ALT", {"blocked": True}),
        _q("RB-0038",
           "Open interest or futures curve shape pays a roll premium in oil.",
           "Hedgers transfer risk along the curve.",
           BLK + " (futures curve)",
           "Spot CrudeOIL treated as the curve.",
           4, 1, 3, 4, 3, "CURVE", {"blocked": True}),
        _q("RB-0039",
           "After a three-day holiday gap, the first print overshoots then fades for a week.",
           "Auctions after closures are noisy.",
           "D1 gap list (max gap 3 days — FACT)",
           "n is tiny. Do not scan gap length.",
           3, 4, 2, 4, 2, "CALENDAR"),
        _q("RB-0040",
           "When USDJPY and EURUSD agree on dollar direction for several days, gold’s residual to that agreement fades.",
           "A slow dollar factor, not a one-day Q3 gate.",
           ALN,
           "Looks like V0.8 with hold=5. Needs a residual definition, not a sign flip.",
           3, 4, 2, 3, 3, "RESIDUAL"),
        _q("RB-0041",
           "Intraday gold mean-reverts around the London fix then trends in NY.",
           "Fixing and US hours are different client sets.",
           "long M15",
           "2000 M15 bars are about a month.",
           3, 1, 4, 1, 2, "SEASONALITY", {"blocked": True}),
        _q("RB-0042",
           "A second Level 1 sleeve with low correlation to the first creates a portfolio premium.",
           "Independent risk premia add. Dependent ones do not.",
           "two Level 1 equity curves + align clock",
           "Building this before any sleeve repeats V0.6.",
           4, 2, 2, 4, 3, "PORTFOLIO"),
        _q("RB-0043",
           "Walk-forward refitting of a locked family finds decay, not a new edge.",
           "Markets adapt. A fixed contract should be stress-tested in time.",
           "D1 + locked ids",
           "Refit becomes a search. Only allowed as a diagnostic after Level 1.",
           2, 5, 2, 4, 4, "VALIDATION", {"meta": True}),
        _q("RB-0044",
           "Funding stress (TED/OIS) forces commodity de-leveraging with a lag.",
           "When dollars are scarce, risk assets are sold to raise cash.",
           BLK + " (funding series)",
           "Using USDJPY as TED.",
           4, 1, 2, 4, 3, "FUNDING", {"blocked": True}),
        _q("RB-0045",
           "After a one-sided gold move with unusually tight spreads, the next week fades as liquidity returns.",
           "A crowded one-way book that later needs an exit.",
           "GOLD D1 spread+return",
           "Spread-low already in FD. Easy kill.",
           2, 5, 3, 3, 3, "LIQUIDITY", {"killed": True}),
        _q("RB-0046",
           "Oil’s extreme negative days are inventory dumps that bounce for more than one bar.",
           "Physical oversupply prints once; paper overshoots.",
           "OIL D1; Qualification already flagged extremes",
           "One-crash sample. Winsor diagnostic is not a hypothesis.",
           2, 5, 3, 2, 2, "PRICE_FORMATION"),
        _q("RB-0047",
           "A locked Δstate edge should appear on both GOLD and OIL if the story is risk-budget, not a metal quirk.",
           "Risk desks cut books, not a single ticker.",
           "GOLD+OIL D1 — already the V0.9 program gate",
           "Gold-only pass = WEAK_EDGE. That is the point of the gate.",
           4, 5, 2, 4, 5, "REGIME_TRANSITION", {"v09": True}),
        _q("RB-0048",
           "Sunday D1 bars are a distinct session; treating them as Monday leaks weekend news into the wrong clock.",
           "This broker prints Sunday D1. Alignment must keep them.",
           "D1 Sunday count from XA audit",
           "This is a clock rule, not an alpha. Still a research question: drop-Sunday as a sensitivity, not a new id.",
           2, 5, 2, 5, 4, "CLOCK", {"meta": True}),
        _q("RB-0049",
           "If costs are halved after seeing losses, a dead family comes back to life.",
           "People will try this. It is not a mechanism.",
           "same bars",
           "Cheating. Expected failure: we refuse the job.",
           1, 5, 5, 1, 5, "PROCESS", {"killed": True}),
        _q("RB-0050",
           "If hold is scanned 3/5/8/10 after a Δstate fail, occupancy and costs change until something passes.",
           "Same cheat as RB-0049 on time.",
           "same bars",
           "New version only. Not V0.9.",
           1, 5, 5, 1, 5, "PROCESS", {"killed": True}),
        _q("RB-0051",
           "A gold/oil residual that is extreme AND a vol transition just happened is a richer warehouse than either alone.",
           "Shock plus mis-relative-price is two constraints.",
           ALN + " + V0.5 VOL",
           "Interaction farm. Only after both parents have their own contracts.",
           3, 4, 2, 3, 2, "INTERACTION"),
        _q("RB-0052",
           "Stop: if every implementable UNKNOWN is later FALSIFIED, the honest alpha is 'no edge in this universe'.",
           "Negative knowledge is still knowledge. It prevents spending years on RSI.",
           "failure database + remaining UNKNOWN=0",
           "Stopping too early while Δstate is untested.",
           2, 5, 1, 5, 5, "STOP", {"meta": True}),
    ]
