"""Machine catalog for ALPHA_BACKLOG_V2. Mechanisms, not indicators."""
from __future__ import print_function


def _m(rid, family, mechanism, asset, timeframe, status, e, d, h, ev, f, nxt, flags=None):
    flags = flags or {}
    return {
        "id": rid,
        "type": "mechanism",
        "family": family,
        "mechanism": mechanism,
        "asset": asset,
        "timeframe": timeframe,
        "status": status,
        "economic_plausibility": e,
        "data_availability": d,
        "historical_coverage": h,
        "existing_evidence": ev,
        "implementation_feasibility": f,
        "data_blocked": bool(flags.get("blocked")),
        "killed_isomorph": bool(flags.get("killed")),
        "v09_member": bool(flags.get("v09")),
        "next_action": nxt,
        "evidence": flags.get("evidence") or "",
    }


def all_mechanisms():
    D1 = "GOLD/OIL"
    return [
        _m("PF-MOM", "Price Formation", "momentum continuation after a same-sign streak",
           "MULTI", "D1/M15", "FAILED", 3, 5, 3, 1, 5, "do_not_repeat HYP-0001/V0.6 MOM-DIR",
           {"killed": True, "evidence": "HYP-0001 + V0.6"}),
        _m("PF-REV", "Price Formation", "mean-reversion of an extended close vs local mean",
           "MULTI", "D1/M15", "FAILED", 3, 5, 3, 1, 5, "do_not_repeat V0.6 MR-Z20",
           {"killed": True, "evidence": "V0.6"}),
        _m("PF-BO", "Price Formation", "breakout through a recent range as a level state",
           "MULTI", "D1", "FAILED", 3, 5, 3, 1, 5, "do_not_repeat V0.5/V0.6 breakout sketches",
           {"killed": True, "evidence": "V0.5/V0.6"}),
        _m("PF-VOLC", "Price Formation", "stay positioned while realized vol is HIGH (level)",
           "OIL", "D1", "FAILED", 3, 5, 3, 1, 5, "level-vol is not a transition; V0.6 skip already used HIGH_VOL",
           {"killed": True, "evidence": "V0.5/V0.6"}),
        _m("MS-RT-LVH", "Market Structure", "low/mid vol -> HIGH vol shock; risk books cut energy",
           "OIL", "D1", "UNKNOWN", 4, 5, 3, 2, 5, "execute HYP-RT-0001",
           {"v09": True, "evidence": "REGIME_TRANSITION_V0.9"}),
        _m("MS-RT-HVL", "Market Structure", "HIGH vol -> LOW vol compression after a shock",
           "OIL", "D1", "UNKNOWN", 3, 5, 3, 2, 4, "not in locked V0.9; do not add HYP-RT-0004",
           {"evidence": "split only; contract has 3 IDs"}),
        _m("MS-RT-WTS", "Market Structure", "WEAK -> STRONG while TREND=UP ignition",
           "GOLD", "D1", "UNKNOWN", 4, 5, 3, 2, 5, "execute HYP-RT-0002",
           {"v09": True, "evidence": "REGIME_TRANSITION_V0.9"}),
        _m("MS-RT-STX", "Market Structure", "STRONG -> WEAK exhaustion / de-risk",
           "GOLD", "D1", "UNKNOWN", 4, 5, 3, 2, 5, "execute HYP-RT-0003",
           {"v09": True, "evidence": "REGIME_TRANSITION_V0.9"}),
        _m("MS-RT-CORR", "Market Structure", "correlation regime shift across GOLD/OIL/FX",
           "MULTI", "D1", "UNKNOWN", 3, 4, 3, 2, 3, "needs a later family; not V0.8 dollar proxy",
           {"evidence": "not contracted"}),
        _m("RV-SPREAD", "Relative Value", "spread formation between GOLD and OIL log prices",
           D1, "D1", "UNKNOWN", 4, 5, 3, 2, 4, "V0.91 parent, not V0.8",
           {"evidence": "CROSS_RESIDUAL_V0.91"}),
        _m("RV-COINT", "Relative Value", "cointegration of GOLD and OIL on a slow factor",
           D1, "D1", "UNKNOWN", 3, 5, 3, 2, 3, "test residual stationarity first",
           {"evidence": "CROSS_RESIDUAL_V0.91"}),
        _m("RV-SHOCK", "Relative Value", "residual shock then fade",
           D1, "D1", "UNKNOWN", 4, 5, 3, 2, 4, "HYP-XR-0001/0002",
           {"evidence": "CROSS_RESIDUAL_V0.91"}),
        _m("RV-MR", "Relative Value", "mean reversion of the GOLD/OIL residual, not next-day FX",
           D1, "D1", "UNKNOWN", 4, 5, 3, 2, 4, "not HYP-XA-0001",
           {"evidence": "CROSS_RESIDUAL_V0.91"}),
        _m("RP-IV", "Risk Premium", "implied vs realized vol",
           "OPTIONS", None, "BLOCKED", 4, 1, 1, 1, 1, "DATA_BLOCKED",
           {"blocked": True, "evidence": "no IV tape"}),
        _m("RP-OPT", "Risk Premium", "options risk premia",
           "OPTIONS", None, "BLOCKED", 4, 1, 1, 1, 1, "DATA_BLOCKED",
           {"blocked": True, "evidence": "no options tape"}),
        _m("RP-CARRY", "Risk Premium", "interest-rate carry",
           "RATES", None, "BLOCKED", 4, 1, 1, 1, 1, "DATA_BLOCKED",
           {"blocked": True, "evidence": "no rates tape"}),
        _m("RP-FUND", "Risk Premium", "funding / basis",
           "FUNDING", None, "BLOCKED", 3, 1, 1, 1, 1, "DATA_BLOCKED",
           {"blocked": True, "evidence": "no funding tape"}),
    ]
