"""Write-once V17 contract. Frozen before any ranking result."""
from __future__ import print_function

from research_engine.cn_a_share_macro_v17 import (
    CAGR_TARGET,
    DENIED,
    EURUSD_HASH,
    EURUSD_ID,
    EXCLUDE_ST,
    FDR_Q,
    FINAL_OOS_ACCESS,
    GVZ_HASH,
    GVZ_ID,
    HOLD_DAYS,
    KEEP_H11_H12,
    LOOKBACKS_ALLOWED,
    MAX_HYPOTHESES,
    MIN_CROSS_SECTION,
    MIN_HISTORY_PAD,
    NEW_H13,
    NEW_PURCHASE,
    PIT_RULE,
    PRICE_DATASET_HASH,
    PRICE_DATASET_ID,
    PRICE_ONLY_REOPEN,
    QUANTILE,
    REOPEN_H11_H12,
    REOPEN_V16,
    RESEARCH,
    SAME_CLUSTER_CORR,
    SEED,
    US500_HASH,
    US500_ID,
    V17_ID,
    VALIDATION,
)
from research_engine.cn_a_share_strategy_v14.cost import COMMISSION, SLIPPAGE, STAMP_NEW, STAMP_OLD, TRANSFER
from research_protocol.hashing import canonical_hash


# Exactly 6. One economic sign per mechanism. Two registered lookbacks. No opposite-sign twin.
HYPOTHESES = (
    {
        "id": "M1_USD_DEF_60",
        "family": "USD_STRENGTH_DEFENSIVE",
        "mechanism": "After USD strengthens, long low USD-beta A-shares. score = -beta_usd_60 * r_usd. r_usd = -r_EURUSD.",
        "lookback": 60,
        "hold_days": 20,
        "macro": "USD_FROM_EURUSD",
        "signal": "NEG_BETA_TIMES_SHOCK",
        "not": "V08_GOLD_OIL_FROM_USD_OR_H11_LOW_VOL",
    },
    {
        "id": "M2_USD_DEF_120",
        "family": "USD_STRENGTH_DEFENSIVE",
        "mechanism": "Same USD-strength defensive, 120-day beta.",
        "lookback": 120,
        "hold_days": 20,
        "macro": "USD_FROM_EURUSD",
        "signal": "NEG_BETA_TIMES_SHOCK",
        "not": "V08_GOLD_OIL_FROM_USD_OR_H11_LOW_VOL",
    },
    {
        "id": "M3_US_CONT_60",
        "family": "GLOBAL_EQUITY_CONTINUATION",
        "mechanism": "After US500 rises, long high US500-beta A-shares. score = beta_us500_60 * r_us500. Risk-on spillover, not A-share residual.",
        "lookback": 60,
        "hold_days": 20,
        "macro": "US500",
        "signal": "BETA_TIMES_SHOCK",
        "not": "V08_OR_PRICE_ONLY_MOMENTUM",
    },
    {
        "id": "M4_US_CONT_120",
        "family": "GLOBAL_EQUITY_CONTINUATION",
        "mechanism": "Same US500 continuation, 120-day beta.",
        "lookback": 120,
        "hold_days": 20,
        "macro": "US500",
        "signal": "BETA_TIMES_SHOCK",
        "not": "V08_OR_PRICE_ONLY_MOMENTUM",
    },
    {
        "id": "M5_GVZ_DEF_60",
        "family": "GOLD_VOL_DEFENSIVE",
        "mechanism": "After GVZ rises, long low GVZ-beta A-shares. score = -beta_gvz_60 * dlog_gvz. Gold-vol risk-off, not realized-vol rank.",
        "lookback": 60,
        "hold_days": 20,
        "macro": "GVZ",
        "signal": "NEG_BETA_TIMES_SHOCK",
        "not": "H11_REALIZED_VOL_OR_INDEX_IV_ON_GOLD",
    },
    {
        "id": "M6_GVZ_DEF_120",
        "family": "GOLD_VOL_DEFENSIVE",
        "mechanism": "Same GVZ defensive, 120-day beta.",
        "lookback": 120,
        "hold_days": 20,
        "macro": "GVZ",
        "signal": "NEG_BETA_TIMES_SHOCK",
        "not": "H11_REALIZED_VOL_OR_INDEX_IV_ON_GOLD",
    },
)


def build_contract():
    if len(HYPOTHESES) != MAX_HYPOTHESES:
        raise RuntimeError("V17_LOCKS_EXACTLY_SIX")
    if any(h["id"].startswith("H11") or h["id"].startswith("H12") or h["id"].startswith("F") or h["id"].startswith("I") for h in HYPOTHESES):
        raise RuntimeError("CLOSED_FAMILY_ID_FORBIDDEN")
    payload = {
        "id": V17_ID,
        "dataset_id": PRICE_DATASET_ID,
        "dataset_hash": PRICE_DATASET_HASH,
        "macro_datasets": {
            "EURUSD": {"id": EURUSD_ID, "sha256": EURUSD_HASH, "role": "USD_PROXY_NEGATED_RETURN"},
            "US500": {"id": US500_ID, "sha256": US500_HASH, "role": "GLOBAL_EQUITY_SHOCK", "coverage_note": "starts_2011-01-17"},
            "GVZ": {"id": GVZ_ID, "sha256": GVZ_HASH, "role": "GOLD_VOL_SHOCK"},
        },
        "unused_short_macros": ["DXY", "UST10", "GOLD", "OIL"],
        "unused_reason": "2018-12 start would silently shrink the locked 2010 research window.",
        "live_api": False,
        "new_purchase": NEW_PURCHASE,
        "ml": False,
        "h11_h12": "KEEP_LOW_PRIORITY",
        "reopen_h11_h12": REOPEN_H11_H12,
        "keep_h11_h12": KEEP_H11_H12,
        "price_only_reopen": PRICE_ONLY_REOPEN,
        "reopen_v16": REOPEN_V16,
        "new_h13": NEW_H13,
        "not": [
            "V08_USD_PREDICTS_GOLD_OIL",
            "H11_H12_RETUNE",
            "V15_RESIDUAL",
            "V16_FINANCIAL_INDUSTRY",
            "OPPOSITE_SIGN_TWIN",
        ],
        "pit_rule": PIT_RULE,
        "signal_price": "RAW_CLOSE_T",
        "execution_price": "RAW_OPEN_T1",
        "return_representation": "RAW_CLOSE_TO_CLOSE",
        "representation_risk": "No frozen QFQ. DIVIDEND_EXCLUSION.",
        "lookbacks_allowed": list(LOOKBACKS_ALLOWED),
        "hold_days": HOLD_DAYS,
        "quantile": QUANTILE,
        "portfolio": "QUINTILE_TOP_20",
        "long_only": True,
        "rebalance": "NON_OVERLAPPING_EVERY_HOLD",
        "predictive_formation": "DAILY_OVERLAPPING_H_DAY",
        "predictive_metric_name": "MEAN_FORWARD_RETURN",
        "predictive_is_not_cagr": True,
        "cagr_only_from": "CANONICAL_CAPITAL_ACCOUNT",
        "exclude_st": EXCLUDE_ST,
        "min_history": "lookback + %s" % MIN_HISTORY_PAD,
        "min_cross_section": MIN_CROSS_SECTION,
        "unexecutable": ["LIMIT_LOCK", "SUSPENDED", "DELISTED", "ZERO_VOLUME", "MISSING_OPEN"],
        "unfilled": "WEIGHT_STAYS_CASH_ZERO_PNL_ZERO_FEE",
        "no_forward_fill_prices": True,
        "research": list(RESEARCH),
        "validation": list(VALIDATION),
        "denied_window": list(DENIED),
        "final_oos": FINAL_OOS_ACCESS,
        "split": "70/15/15_TIME",
        "fdr_q": FDR_Q,
        "seed": SEED,
        "cost_model": {
            "id": "A_SHARE_STRATEGY_COST_MODEL_V1",
            "commission": COMMISSION,
            "transfer": TRANSFER,
            "slippage": SLIPPAGE,
            "stamp_before_20230828": STAMP_OLD,
            "stamp_from_20230828": STAMP_NEW,
            "stamp_side": "SELL_ONLY",
            "optimize": False,
        },
        "same_cluster_corr": SAME_CLUSTER_CORR,
        "cagr_target_not_a_gate": CAGR_TARGET,
        "level1": [
            "pre_registered",
            "research_MEAN_FORWARD_RETURN_net > 0",
            "validation_MEAN_FORWARD_RETURN_net > 0",
            "BH_FDR_q_0.05",
            ">=2 evidence (excess_vs_B0 and rank_ic) on research AND validation",
            "PIT_clean",
            "research_capital_total > 0",
            "validation_capital_total > 0",
        ],
        "do_not_flip_sign": True,
        "preregistered_run_all_six": True,
        "hypotheses": [dict(h) for h in HYPOTHESES],
    }
    payload["contract_hash"] = canonical_hash(payload)
    return payload
