"""Classify information sources. Price direction is already FAILED. Not V0.8 again."""
from __future__ import print_function


def all_sources():
    return [
        {
            "id": "INFO-PRICE",
            "class": "A_PRICE",
            "status": "FAILED",
            "mechanism": "Own-price continuation / reversal / breakout at short horizon",
            "data_on_disk": True,
            "previously_tested": True,
            "families": ["HYP-0001", "FD_V0.1", "V0.5", "V0.6"],
            "note": "Do not add RSI/MACD/MA.",
        },
        {
            "id": "INFO-XASSET-PROXY",
            "class": "B_CROSS_ASSET",
            "status": "FAILED",
            "mechanism": "Next-day dollar-proxy (USDJPY/EURUSD -> GOLD/OIL)",
            "data_on_disk": True,
            "previously_tested": True,
            "families": ["V0.8"],
            "note": "Wrong relative-value object. Do not reopen.",
        },
        {
            "id": "INFO-RESIDUAL",
            "class": "B_CROSS_ASSET",
            "status": "FAILED",
            "mechanism": "GOLD/OIL log-spread residual fade",
            "data_on_disk": True,
            "previously_tested": True,
            "families": ["V0.91"],
            "note": "Cost ate the book. Do not retune SMA60.",
        },
        {
            "id": "INFO-RV-TERM",
            "class": "C_VOLATILITY",
            "status": "UNKNOWN",
            "mechanism": "Realized-vol term structure from OHLC (short RV vs long RV), not IV",
            "data_on_disk": True,
            "previously_tested": False,
            "families": [],
            "note": "IV is BLOCKED. ATR percentile buckets were tested; term structure was not.",
            "can_build_from_ohlc": True,
        },
        {
            "id": "INFO-VOVOL",
            "class": "C_VOLATILITY",
            "status": "UNKNOWN",
            "mechanism": "Volatility of realized volatility from ATR/TR series",
            "data_on_disk": True,
            "previously_tested": False,
            "families": [],
            "note": "Adjacent to V0.9 VOL_SHOCK (enter HIGH). Higher isomorph risk.",
            "can_build_from_ohlc": True,
        },
        {
            "id": "INFO-IV",
            "class": "C_VOLATILITY",
            "status": "BLOCKED",
            "mechanism": "IV / VRP / options",
            "data_on_disk": False,
            "previously_tested": False,
            "families": [],
            "note": "DATA_BLOCKED. Do not invent IV.",
        },
        {
            "id": "INFO-MONTH-END",
            "class": "D_TIME",
            "status": "UNKNOWN",
            "mechanism": "Month-end / month-start benchmark and dealer inventory windows",
            "data_on_disk": True,
            "previously_tested": False,
            "families": [],
            "note": "Not weekday dummies. D1 timestamps are enough.",
        },
        {
            "id": "INFO-QUARTER-END",
            "class": "D_TIME",
            "status": "UNKNOWN",
            "mechanism": "Quarter-end window dressing / risk-budget reset",
            "data_on_disk": True,
            "previously_tested": False,
            "families": [],
            "note": "Fewer events than month-end. Power risk.",
        },
        {
            "id": "INFO-LONDON-OPEN",
            "class": "D_TIME",
            "status": "UNKNOWN",
            "mechanism": "London cash open inventory / spread shock",
            "data_on_disk": False,
            "previously_tested": False,
            "families": [],
            "note": "Frozen H1 is months. Read-only probe meets ~5.03y H1 as new IDs only. Not selected this round.",
        },
        {
            "id": "INFO-NY-OPEN",
            "class": "D_TIME",
            "status": "UNKNOWN",
            "mechanism": "New York open overlap flow",
            "data_on_disk": False,
            "previously_tested": False,
            "families": [],
            "note": "Same as London: probe can freeze 5y H1; immutable packs cannot.",
        },
        {
            "id": "INFO-ROLL",
            "class": "D_TIME",
            "status": "BLOCKED",
            "mechanism": "Futures roll window",
            "data_on_disk": False,
            "previously_tested": False,
            "families": [],
            "note": "No roll tape. Broker CFD continuous series is not a roll calendar.",
        },
        {
            "id": "INFO-VOL-SURPRISE",
            "class": "E_MICROSTRUCTURE",
            "status": "UNKNOWN",
            "mechanism": "Tick-volume surprise vs its own recent baseline",
            "data_on_disk": True,
            "previously_tested": False,
            "families": [],
            "note": "FD killed tickvol_z as a next-return *level*. Surprise/divergence was not the contract.",
        },
        {
            "id": "INFO-VOL-DIVERGE",
            "class": "E_MICROSTRUCTURE",
            "status": "UNKNOWN",
            "mechanism": "Volume up while return is small or opposite (absorption / disagreement)",
            "data_on_disk": True,
            "previously_tested": False,
            "families": [],
            "note": "tick_volume is present. Not a delete. Not an RSI.",
        },
        {
            "id": "INFO-RISK-ONOFF",
            "class": "F_MACRO_PROXY",
            "status": "UNKNOWN",
            "mechanism": "Same-day joint sign of GOLD/OIL/FX as a risk-on/off *label*, not a next-day GOLD forecast",
            "data_on_disk": True,
            "previously_tested": False,
            "families": [],
            "note": "V0.8 predicted next GOLD/OIL from FX. A label without a new target is not alpha.",
        },
        {
            "id": "INFO-USD-PROXY",
            "class": "F_MACRO_PROXY",
            "status": "FAILED",
            "mechanism": "USD strength from EURUSD+USDJPY to trade GOLD tomorrow",
            "data_on_disk": True,
            "previously_tested": True,
            "families": ["V0.8"],
            "note": "Isomorph of V0.8. Score must be zero.",
            "killed_isomorph": True,
        },
        {
            "id": "INFO-COMMOD-BASKET",
            "class": "F_MACRO_PROXY",
            "status": "UNKNOWN",
            "mechanism": "Equal-weight GOLD+OIL residual vs a single leg",
            "data_on_disk": True,
            "previously_tested": False,
            "families": [],
            "note": "Close to V0.91. High isomorph risk.",
        },
    ]
